version: "3"

services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./data:/data
    restart: always
